commands:
  aliases:
    - "sc"
    - "staffc"
discord:
  bot-token: "OTEzNjM4MDI3MDMxNjA5NDE2.YaBZuA.UNoErRnkCLrKHLjrynTeiCLruA0"
  channel-id: "913637065084780588"
  status:
    type: LISTENING
    message: "Hola"

staff-list:
  delimiter: ", "
  format: "%server% - (%staffs%)"

server-switch:
  on-join: |-
    &c%player% ha entrado
    &aPrueba2
  on-new-join: |-
    &a
    &a%player% ha entrando con nueva nueva ip (%lastip% - %newip%)
    &a
  on-change-server: |-
    &a
    &c%player% &cha cambiado de %from% a %to%
    &a

staff-chat:
  toggle:
    enable: "&aHas togleado el staffchat"
    disable: "&cHas destogleado el staffchat"
  permission: "staffchat.use"
  usage: "/sc <message | or subcommands>"
  format: "&cSTAFFCHAT | &5%player%&7: &f%message%"